# Generated by Django 4.2 on 2023-05-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="photo",
            field=models.ImageField(upload_to="Images"),
        ),
        migrations.AlterField(
            model_name="normaluser",
            name="photo",
            field=models.ImageField(upload_to="Images"),
        ),
    ]
