# Generated by Django 4.2 on 2023-05-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_managers_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
