# Generated by Django 4.2 on 2023-05-25 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_artist_is_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
