# Generated by Django 4.2 on 2023-04-28 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sponser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sponser_type",
                    models.CharField(
                        choices=[
                            ("Title Sponser", "title sponser"),
                            ("Platinum", "platinum"),
                            ("Gold", "gold"),
                            ("Silver", "silver"),
                            ("Bronze", "bronze"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-z- A-z]+$",
                                code="Invalid name",
                                message="Invalide data to the fields........",
                            )
                        ],
                    ),
                ),
                ("amount", models.BigIntegerField()),
            ],
        ),
    ]
