# Generated by Django 4.2 on 2023-09-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_completed',
            field=models.BooleanField(default=False),
        ),
    ]
